# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: robinet 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "robinet"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ali-Akber Saifee"]
  s.date = "2017-03-26"
  s.description = "Rate limiting for rack applications"
  s.email = "ali@indydevs.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".overcommit.yml",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/robinet.rb",
    "lib/robinet/config.rb",
    "lib/robinet/limit.rb",
    "lib/robinet/parser.rb",
    "lib/robinet/storage.rb",
    "lib/robinet/storage/memory.rb",
    "lib/robinet/strategy.rb",
    "lib/robinet/strategy/fixed_window.rb",
    "spec/parser_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/alisaifee/robinet"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Rate limiting for rack applications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<robinet>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.3"])
      s.add_development_dependency(%q<overcommit>, ["~> 0.33"])
      s.add_development_dependency(%q<reek>, ["~> 4.1"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.44"])
      s.add_runtime_dependency(%q<dry-configurable>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.3"])
      s.add_development_dependency(%q<overcommit>, ["~> 0.33"])
      s.add_development_dependency(%q<reek>, ["~> 4.1"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.44"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<robinet>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.3"])
      s.add_dependency(%q<overcommit>, ["~> 0.33"])
      s.add_dependency(%q<reek>, ["~> 4.1"])
      s.add_dependency(%q<rubocop>, ["~> 0.44"])
      s.add_dependency(%q<dry-configurable>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.3"])
      s.add_dependency(%q<overcommit>, ["~> 0.33"])
      s.add_dependency(%q<reek>, ["~> 4.1"])
      s.add_dependency(%q<rubocop>, ["~> 0.44"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.1.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<robinet>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.3"])
    s.add_dependency(%q<overcommit>, ["~> 0.33"])
    s.add_dependency(%q<reek>, ["~> 4.1"])
    s.add_dependency(%q<rubocop>, ["~> 0.44"])
    s.add_dependency(%q<dry-configurable>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.3"])
    s.add_dependency(%q<overcommit>, ["~> 0.33"])
    s.add_dependency(%q<reek>, ["~> 4.1"])
    s.add_dependency(%q<rubocop>, ["~> 0.44"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.1.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

